"""Shared transcription workflow used by the HTTP API and offline CLI."""

from __future__ import annotations

import json
import os
import re
import tempfile
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from app.monitoring.metrics import ResourceSampler
from app.transcription.markdown import write_markdown_atomic
from app.transcription.models import Segment
from app.transcription.paths import resolve_input_path
from app.transcription.whisper import Transcriber


def _package_version(package: str) -> str:
    try:
        return version(package)
    except PackageNotFoundError:
        return "unknown"


def _write_json_atomic(destination: Path, payload: dict) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary = handle.name
            json.dump(payload, handle, ensure_ascii=False, indent=2)
            handle.write("\n")
        os.replace(temporary, destination)
    finally:
        if temporary is not None and os.path.exists(temporary):
            os.unlink(temporary)


def _artifact_stem(source: Path, job_id: str) -> str:
    # The ID is supplied by the job manager or generated by the CLI.
    safe_name = re.sub(r"[^\w-]+", "-", source.stem, flags=re.UNICODE).strip("-_")[:80]
    safe_id = re.sub(r"[^a-zA-Z0-9-]", "", job_id)
    if not safe_id:
        raise ValueError("Identificador de job inválido")
    return f"{safe_name or 'media'}.{safe_id}"


def public_result_payload(
    job_id: str, segments: list[Segment], duration_seconds: float
) -> dict:
    """Convert engine values to the stable, versioned public result shape."""
    return {
        "schemaVersion": 1,
        "jobId": job_id,
        "language": "pt-BR",
        "durationMs": int(round(duration_seconds * 1000)),
        "segments": [
            {
                "startMs": max(0, int(round(float(segment.start) * 1000))),
                "endMs": max(0, int(round(float(segment.end) * 1000))),
                "text": str(segment.text),
            }
            for segment in segments
        ],
    }


def _metrics_payload(
    *,
    source: Path,
    transcriber: Transcriber,
    duration_seconds: float | None,
    elapsed_seconds: float,
    sampler: ResourceSampler,
    status: str,
) -> dict:
    rtf = (
        elapsed_seconds / duration_seconds
        if duration_seconds and duration_seconds > 0
        else None
    )
    speed = (
        duration_seconds / elapsed_seconds
        if duration_seconds and elapsed_seconds > 0
        else None
    )
    threads = transcriber.cpu_threads
    return {
        "input": {
            "file": source.name,
            "sizeMb": round(source.stat().st_size / 1_000_000, 2),
            "durationSeconds": duration_seconds,
        },
        "whisper": {
            "model": transcriber.model_name,
            "device": "cpu",
            "computeType": "int8",
            "beamSize": 5,
            "vad": True,
            "language": "pt",
            "wordTimestamps": False,
        },
        "runtime": {
            "cpuLimit": float(os.getenv("CPU_LIMIT", str(threads))),
            "cpuThreads": threads,
            "concurrency": 1,
        },
        "processing": {
            "modelLoadSeconds": round(transcriber.model_load_seconds, 3),
            "elapsedSeconds": round(elapsed_seconds, 3),
            "realtimeFactor": round(rtf, 4) if rtf is not None else None,
            "speedFactor": round(speed, 3) if speed is not None else None,
            "status": status,
        },
        "resources": sampler.summary(),
        "software": {
            "applicationVersion": os.getenv("APP_VERSION", "0.1.0"),
            "fasterWhisperVersion": _package_version("faster-whisper"),
        },
    }


def run_transcription(
    relative_path: str, job_id: str, transcriber: Transcriber
) -> dict:
    """Transcribe one validated media file and return API result fields.

    The CLI and API call this same function. Files are named using the job ID
    so repeated benchmarks never overwrite an earlier result.
    """
    input_dir = Path(os.getenv("APP_INPUT_DIR", "/data/input"))
    output_dir = Path(os.getenv("APP_OUTPUT_DIR", "/data/output"))
    source = resolve_input_path(relative_path, input_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = _artifact_stem(source, job_id)
    markdown_path = output_dir / f"{stem}.md"
    metrics_path = output_dir / f"{stem}.metrics.json"

    sampler = ResourceSampler(interval_seconds=1.0)
    sampler.start()
    sampling = True
    elapsed = 0.0
    duration: float | None = None
    try:
        segments, duration = transcriber.transcribe(source)
        elapsed = sampler.stop()
        sampling = False
        write_markdown_atomic(
            markdown_path,
            source.name,
            segments,
            duration_seconds=duration,
            model_name=transcriber.model_name,
            cpu_threads=transcriber.cpu_threads,
            elapsed_seconds=elapsed,
        )
        metrics = _metrics_payload(
            source=source,
            transcriber=transcriber,
            duration_seconds=duration,
            elapsed_seconds=elapsed,
            sampler=sampler,
            status="completed",
        )
        _write_json_atomic(metrics_path, metrics)
    except Exception:
        if sampling:
            elapsed = sampler.stop()
        try:
            failure_metrics = _metrics_payload(
                source=source,
                transcriber=transcriber,
                duration_seconds=duration,
                elapsed_seconds=elapsed,
                sampler=sampler,
                status="failed",
            )
            _write_json_atomic(metrics_path, failure_metrics)
        except Exception:
            # Preserve the original error; the worker logs the full traceback.
            pass
        raise

    return {
        "output": markdown_path.name,
        "metricsOutput": metrics_path.name,
        "metrics": {
            "mediaDurationSeconds": duration,
            "processingSeconds": round(elapsed, 3),
            "realtimeFactor": metrics["processing"]["realtimeFactor"],
            "speedFactor": metrics["processing"]["speedFactor"],
            "peakMemoryMb": metrics["resources"]["peakMemoryMb"],
        },
    }
